<a href="https://colab.research.google.com/github/Sebastian-Constantin-Iacob/learning_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors
### Creating tensors
### PyTorch tensors are created using torch.Tensor(). See documentation at: https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# A scalar has 0 dimentions
scalar.ndim

0

In [4]:
# We can get the tensor back, in this case as a Python int
scalar.item()

7

In [5]:
# A vector as a tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# A vector is considered as having 1 dimention
vector.ndim

1

In [7]:
# A vector can not be retrived as an item
vector.item()

RuntimeError: ignored

In [8]:
# We can get the shape of a vacor 
vector.shape

torch.Size([2])

In [10]:
# Creating a MATRIX
MATRIX = torch.tensor([[7 ,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Numbers of dimentions for a MATRIX
MATRIX.ndim

2

In [15]:
# The shape of a MATRIX
MATRIX.shape

torch.Size([2, 2])

In [19]:
# Accesing the rows of a matrix
MATRIX[0]

tensor([7, 8])

In [20]:
# Accesing the rows of a matrix
MATRIX[1]

tensor([ 9, 10])

In [21]:
# A tensor that is a larger matrix ( 3x3 )
TENSOR = torch.tensor([[[1, 2, 3],
                      [3, 6, 9],
                      [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
# Tensor dimentions
TENSOR.ndim

3

In [24]:
# The shape of a 3x3 tensor ( we can read it as one three by three tensor (1, 3, 3) )
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
Why random tensors ?

Random tensors are important because the way many neural networks learn, is that they start with tensors full of random numbers, and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers etc`

In [25]:
# Create a random tensor of size (3, 4) < https://pytorch.org/docs/stable/generated/torch.rand.html >
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9198, 0.5913, 0.9677, 0.7077],
        [0.7111, 0.8037, 0.1164, 0.5330],
        [0.9095, 0.6209, 0.8629, 0.0363]])

In [26]:
# Dimentions of this random tensor
random_tensor.ndim

2

In [27]:
# Create a random tensor, with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, color channel RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

## Zeros and ones tensors

In [29]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
# As we can see we are using floats by default
ones.type()

'torch.FloatTensor'

In [33]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [34]:
# Using torch.range() - Depricated use torch.arange(start, end, step)
torch.range(0, 10)

<ipython-input-34-9e8d4bb9e1be>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
# Using torch.arange()
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Creating tensors like ( for example a particular shape of tensor )
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 
## https://pytorch.org/docs/stable/tensors.html
**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch & deep learning:
1. Tensors not right dataype
2. Tensors not right shape
3. Tensors not on right device

In [43]:
# Creating a float32 tensor
float_32_tensor = torch.tensor([3., 6., 9.],
                               dtype=None, # What data type is the tensor
                               device=None, # What device the tensor is on
                               requires_grad=False) # Wether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [41]:
# As we can see, the default data type in torch is float32
float_32_tensor.dtype

torch.float32

In [42]:
# Let us do a floar 16 tensor for example
float_16_tensor = torch.tensor([5, 5, 7],
                               dtype=torch.float16)
float_16_tensor

tensor([5., 5., 7.], dtype=torch.float16)

In [44]:
# A different way of creating a 16 bit tensor from a 32 bit tensor
float_16_tensor_b = float_32_tensor.type(torch.float16)
float_16_tensor_b

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
# Experiment of multiplying 2 tensors of different data types
tensor_32x16 = float_32_tensor * float_16_tensor
tensor_32x16

tensor([15., 30., 63.])

In [47]:
# What data type dose it have now? ( I think before running the experiment that it will convert it up )
tensor_32x16.dtype

torch.float32

In [49]:
# Let us run an experiment with operations between int and float tensors
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor, int_32_tensor * float_32_tensor

(tensor([3, 6, 9], dtype=torch.int32), tensor([ 9., 36., 81.]))

### Getting information from tensors

1.Tensors not right dataype - `tensor.dtype` <br>
2.Tensors not right shape - `tensor.shape`<br>
3.Tensors not on right device - `tensor.device`<br>

In [50]:
# Create a random tensor , to do some experiments
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.0014, 0.5257, 0.8500, 0.1863],
        [0.5505, 0.4522, 0.1669, 0.3253],
        [0.6138, 0.0272, 0.6315, 0.6074]])

In [51]:
# Let us see the default attributes of a random tensor
print(f"The actual tensor: {some_tensor}")
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device the tensor is on: {some_tensor.device}")

The actual tensor: tensor([[0.0014, 0.5257, 0.8500, 0.1863],
        [0.5505, 0.4522, 0.1669, 0.3253],
        [0.6138, 0.0272, 0.6315, 0.6074]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device the tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [52]:
# Create a random tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [53]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [54]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [55]:
# Try out PyTorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [56]:
torch.add(tensor, -10)

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing matrix multiplication:
1. Element-wise multiplication
2. Matrix multiplication ( the dor product )

In [58]:
# Element wise multiplication
print(f"{tensor} * {tensor} = {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [59]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [60]:
# Matrix multiplication on actual matrix ( not vectors )
MATRIX_A = torch.tensor([[1, 2],
                         [3, 4]])
MATRIX_B = torch.tensor([[5, 6],
                         [7, 8]])
torch.matmul(MATRIX_A, MATRIX_B)

tensor([[19, 22],
        [43, 50]])