<a href="https://colab.research.google.com/github/Sebastian-Constantin-Iacob/learning_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors
### Creating tensors
### PyTorch tensors are created using torch.Tensor(). See documentation at: https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# A scalar has 0 dimentions
scalar.ndim

0

In [4]:
# We can get the tensor back, in this case as a Python int
scalar.item()

7

In [5]:
# A vector as a tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# A vector is considered as having 1 dimention
vector.ndim

1

In [7]:
# A vector can not be retrived as an item
vector.item()

RuntimeError: ignored

In [8]:
# We can get the shape of a vacor 
vector.shape

torch.Size([2])

In [10]:
# Creating a MATRIX
MATRIX = torch.tensor([[7 ,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Numbers of dimentions for a MATRIX
MATRIX.ndim

2

In [15]:
# The shape of a MATRIX
MATRIX.shape

torch.Size([2, 2])

In [19]:
# Accesing the rows of a matrix
MATRIX[0]

tensor([7, 8])

In [20]:
# Accesing the rows of a matrix
MATRIX[1]

tensor([ 9, 10])

In [21]:
# A tensor that is a larger matrix ( 3x3 )
TENSOR = torch.tensor([[[1, 2, 3],
                      [3, 6, 9],
                      [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
# Tensor dimentions
TENSOR.ndim

3

In [24]:
# The shape of a 3x3 tensor ( we can read it as one three by three tensor (1, 3, 3) )
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
Why random tensors ?

Random tensors are important because the way many neural networks learn, is that they start with tensors full of random numbers, and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers etc`

In [25]:
# Create a random tensor of size (3, 4) < https://pytorch.org/docs/stable/generated/torch.rand.html >
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9198, 0.5913, 0.9677, 0.7077],
        [0.7111, 0.8037, 0.1164, 0.5330],
        [0.9095, 0.6209, 0.8629, 0.0363]])

In [26]:
# Dimentions of this random tensor
random_tensor.ndim

2

In [27]:
# Create a random tensor, with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, color channel RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)